"""Build interactive_demo/v2/data/tab5_adaptive.json.

Direct re-export of interactive_demo/data/stage6_10_bundle.json (already
built by stage6_10_emergence_adaptive_control/code/export_demo_data_610.py
for exactly this purpose: one representative 20x20 online closed-loop
episode -- emergence, detection, adaptive steering with online re-inference,
release). That bundle's own provenance block already documents that
per-timestep headings were regenerated by a deterministic replay of the
frozen simulator at the same seed/regime/action-sequence, with every
replayed quantity asserted equal to the frozen result file (see its
"replay_note"). We do not touch that replay here -- only re-serve the file,
trimmed of the multi-episode arm_summary detail the demo doesn't need.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = Path(__file__).resolve().parents[2] / "data" / "tab5_adaptive.json"

d = json.load(open(ROOT / "interactive_demo/data/stage6_10_bundle.json"))

out = {
    "provenance": d["provenance"],
    "lattice": d["lattice"],
    "episode": d["episode"],
    "frames": d["frames"],
    "emergence": d["emergence"],
    "control": d["control"],
    "release": d["release"],
    "no_control": d["no_control"],
    "phases": d["phases"],
    "task": d["task"],
    "envelope": d["envelope"],
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(out))
print("wrote", OUT, OUT.stat().st_size, "bytes")
