"""Task A (spec S5): harden ForwardMaterialTrace611's validation WITHOUT
making the tracker more complex. Does NOT retune the frozen rule
(Jaccard >= 0.30, from material_identity_step2_20260921). This script only
TESTS it, harder, than Step 2's own cross-episode-unrelated-pair calibration
did.

Two natural-data splits, disjoint by EPISODE (never by row), both under the
identical PRIMARY regime as the frozen rule's own calibration data:

  DEV / already-used-for-calibration : data/observational_corpus_611__val.npz
      seeds 236-247 (12 episodes). This is the exact corpus
      calibrate_identity_rule.py used to select Jaccard>=0.30. Re-analyzed
      here with a HARDER negative construction (same-episode, same-frame
      distractors instead of cross-episode pairs), but the threshold itself
      is never touched.

  UNTOUCHED VALIDATION : data/observational_corpus_611__test.npz
      seeds 248-259 (12 episodes). Generated by observational_corpus_611.py
      at the same primary regime, but never read by ANY prior Step-1/Step-2
      script (grep-verified: only *_611.py training/predictive-model code
      and this script touch this file). This is the genuine held-out set
      task S5.2 asks for -- no new simulation needed, the file already
      existed on disk from the predictive-model corpus build.

Two analyses, per split:

(1) SAME-FRAME HARD NEGATIVES (S5.1). Step 2's own calibration negatives
    were candidates drawn from DIFFERENT episodes -- an easy case (different
    random initial condition, likely different region of state space
    entirely). The real adversarial case is a distractor candidate
    co-present in the SAME episode, SAME transition (t -> t+1): another
    flock, a spatially nearby group, a split daughter, a candidate that
    overlaps partially. For every candidate c at (episode, t) with
    len(c)>=5, and its own best-Jaccard match at t+1 (the "presumed
    continuation" -- what a tracker actually chasing this candidate would
    compare against), every OTHER candidate at t+1 is a hard negative
    against c. Categorized (never silently labelled "ground truth
    negative"):
      - zero_overlap: jaccard==0 with c -- the only case this pass calls
        "obvious unrelated" (no material relationship at this transition).
      - nonzero_below_threshold: 0 < jaccard < 0.30.
      - AT_OR_ABOVE_THRESHOLD: jaccard >= 0.30 -- the dangerous case: an
        unrelated (non-chosen) same-frame candidate that the frozen rule
        would itself also accept, had it been offered as the only
        candidate. This is the number Step 2's cross-episode-only
        calibration could not see.
    Stratified by target size bucket and by spatial proximity (torus-aware
    centroid distance at t+1, bucketed relative to the episode's own local
    density scale, geometry_611.local_scale -- never the true interaction
    radius).

(2) EPISODE-LEVEL SEQUENTIAL TRACE AUDIT (S5.3). ForwardMaterialTrace611
    run forward, full episode, from several seed targets per episode
    (largest 3 candidates at t=5, skipping the very first few detector-
    warmup steps). No control, no target heading, no outcome -- pure
    identity behaviour on natural data. Per trace: final status, number of
    unresolved episodes and their durations, number of recoveries, number
    of split/merge flags, cumulative turnover (1 - jaccard(members at
    trace-start, members at trace-end)), max duration reached.
    "Erroneous transfer" cannot be scored against an omniscient ground-truth
    label (none exists for real simulated flocks -- this pass does not
    invent one). Instead this pass reports the rule's own internal
    consistency signals -- because ForwardMaterialTrace611 structurally
    cannot accept a step whose jaccard-to-previous is below threshold, a
    "false switch" can only happen at the moment of an accepted step: this
    pass separately reports, at every accepted continuing step, the JACCARD
    MARGIN between the winning candidate and the runner-up (if any other
    candidate also passed the gate) -- a small margin is a risk signal for
    ambiguity, not proof of a wrong choice.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

STAGE_DIR = Path(__file__).resolve().parents[3]
CODE_DIR = STAGE_DIR / "code"
sys.path.insert(0, str(CODE_DIR))

from common_611 import DATA_DIR, L_BOX  # noqa: E402
from detect_69 import propose  # noqa: E402
import run_online_control_611 as ROC  # noqa: E402
import geometry_611 as geo  # noqa: E402

STEP2_CODE = STAGE_DIR / "audit" / "material_identity_step2_20260921" / "code"
sys.path.insert(0, str(STEP2_CODE))
from forward_material_trace_611 import (  # noqa: E402
    ForwardMaterialTrace611, overlap_metrics, RULE_FAMILY_BUILDERS,
)

OUT_DATA = Path(__file__).resolve().parents[1] / "data"
FROZEN_JSON = STEP2_CODE.parent / "data" / "identity_rule_calibration.json"

SPLITS = {
    "dev_already_used_for_calibration": DATA_DIR / "observational_corpus_611__val.npz",
    "untouched_validation": DATA_DIR / "observational_corpus_611__test.npz",
}


def load_frozen_rule():
    calib = json.load(open(FROZEN_JSON))
    frozen = calib["frozen_rule"]
    rule = RULE_FAMILY_BUILDERS[frozen["letter"]](**frozen["params"])
    return rule, frozen


def run_episode_candidates(r_hist, z_hist, L, stride=1):
    """Identical method to calibrate_identity_rule.py's helper (kept
    duplicated, not imported, so this hardening pass does not silently
    inherit a bug in the original calibration's candidate generation without
    re-deriving it independently)."""
    T = r_hist.shape[0]
    z_window = []
    out = []
    for t in range(0, T, stride):
        z_window.append(z_hist[t])
        if len(z_window) > ROC.AFFINITY_WINDOW:
            z_window.pop(0)
        cands = propose(r_hist[t], z_window, L) if len(z_window) >= 2 else []
        out.append([frozenset(int(x) for x in c) for c in cands])
    return out


def torus_centroid(members, r, L):
    """Circular-mean torus-aware centroid (angle-average per axis, mapped
    back into [0, L)). Consistent with geometry_611.torus_delta's wrap
    convention."""
    pts = r[list(members)]
    theta = pts / L * 2 * np.pi
    c = np.arctan2(np.sin(theta).mean(axis=0), np.cos(theta).mean(axis=0))
    return (c / (2 * np.pi) * L) % L


def best_jaccard_match(c, next_cands):
    best, best_j, best_idx = None, -1.0, None
    for idx, c2 in enumerate(next_cands):
        u = len(c | c2)
        j = (len(c & c2) / u) if u else 0.0
        if j > best_j:
            best_j, best, best_idx = j, c2, idx
    return best, best_j, best_idx


def size_bucket(n):
    if n < 20:
        return "small(<20)"
    if n < 50:
        return "medium(20-49)"
    return "large(>=50)"


def same_frame_hard_negatives(episode_candidates, r_hist_by_seed, L, rule):
    """(1) above. Returns flat list of hard-negative records."""
    records = []
    for seed, cands_by_t in episode_candidates.items():
        r_hist = r_hist_by_seed[seed]
        local_scale = geo.local_scale(r_hist[0], L)
        for t in range(len(cands_by_t) - 1):
            cur_cands = [c for c in cands_by_t[t] if len(c) >= 5]
            next_cands = cands_by_t[t + 1]
            if not next_cands:
                continue
            for c in cur_cands:
                match, best_j, match_idx = best_jaccard_match(c, next_cands)
                if match is None:
                    continue
                c_next_centroid = torus_centroid(match, r_hist[t + 1], L) if len(match) else None
                for idx, other in enumerate(next_cands):
                    if idx == match_idx:
                        continue
                    if len(other) == 0:
                        continue
                    m = overlap_metrics(c, other)
                    if m["jaccard"] == 0.0:
                        category = "zero_overlap"
                    elif m["jaccard"] >= 0.30:
                        category = "AT_OR_ABOVE_THRESHOLD"
                    else:
                        category = "nonzero_below_threshold"
                    # Both centroids at t+1 (same instant): "nearby" must mean
                    # spatially co-located with the TRUE continuation at the
                    # same moment, not merely close to the t-frame target's
                    # own position one step earlier (which conflates ordinary
                    # one-step flock translation with genuine spatial
                    # adjacency of a distractor).
                    other_centroid = torus_centroid(other, r_hist[t + 1], L)
                    match_centroid = c_next_centroid
                    delta = geo.torus_delta(other_centroid, match_centroid, L)
                    dist = float(np.sqrt((delta ** 2).sum()))
                    proximity = "spatially_nearby" if dist <= 2.5 * local_scale else "spatially_far"
                    records.append(dict(
                        seed=int(seed), t=t, target_size=len(c), other_size=len(other),
                        size_bucket=size_bucket(len(c)),
                        jaccard=m["jaccard"], R_old=m["R_old"], R_new=m["R_new"],
                        retained=m["retained"],
                        category=category, proximity=proximity,
                        centroid_distance=dist, local_scale=float(local_scale),
                        rule_would_accept=bool(m["jaccard"] >= 0.30),
                    ))
    return records


def summarize_hard_negatives(records, split_name):
    n = len(records)
    n_accept = sum(1 for r in records if r["rule_would_accept"])
    by_bucket = {}
    for bucket in ("small(<20)", "medium(20-49)", "large(>=50)"):
        sub = [r for r in records if r["size_bucket"] == bucket]
        if not sub:
            continue
        by_bucket[bucket] = dict(
            n=len(sub),
            n_at_or_above_threshold=sum(1 for r in sub if r["rule_would_accept"]),
            fraction_at_or_above_threshold=sum(1 for r in sub if r["rule_would_accept"]) / len(sub),
        )
    by_proximity = {}
    for prox in ("spatially_nearby", "spatially_far"):
        sub = [r for r in records if r["proximity"] == prox]
        if not sub:
            continue
        by_proximity[prox] = dict(
            n=len(sub),
            n_at_or_above_threshold=sum(1 for r in sub if r["rule_would_accept"]),
            fraction_at_or_above_threshold=sum(1 for r in sub if r["rule_would_accept"]) / len(sub),
        )
    category_counts = {}
    for cat in ("zero_overlap", "nonzero_below_threshold", "AT_OR_ABOVE_THRESHOLD"):
        category_counts[cat] = sum(1 for r in records if r["category"] == cat)
    return dict(
        split=split_name, n_hard_negative_pairs=n,
        n_at_or_above_threshold=n_accept,
        fraction_at_or_above_threshold=(n_accept / n) if n else None,
        category_counts=category_counts,
        by_size_bucket=by_bucket,
        by_spatial_proximity=by_proximity,
    )


def episode_level_trace_audit(episode_candidates, rule, n_seed_targets_per_episode=3, start_t=5):
    """(2) above."""
    per_episode = []
    for seed, cands_by_t in episode_candidates.items():
        if start_t >= len(cands_by_t):
            continue
        seed_cands = sorted(cands_by_t[start_t], key=len, reverse=True)[:n_seed_targets_per_episode]
        traces_summary = []
        for target_idx, seed_target in enumerate(seed_cands):
            if len(seed_target) < 10:
                continue
            tr = ForwardMaterialTrace611(rule)
            tr.start(start_t, seed_target)
            n_unresolved = 0
            n_recovered = 0
            n_split = 0
            n_merge = 0
            gap_lengths = []
            cur_gap = 0
            margins = []
            prev_status = "continuing"
            for t in range(start_t + 1, len(cands_by_t)):
                d = tr.step(t, cands_by_t[t])
                if d.status == "unresolved":
                    n_unresolved += 1
                    cur_gap += 1
                else:
                    if cur_gap > 0:
                        gap_lengths.append(cur_gap)
                        if d.status == "continuing":
                            n_recovered += 1
                        cur_gap = 0
                if d.status == "continuing" and d.n_accepting_candidates > 1:
                    accepting_j = sorted(
                        (m["jaccard"] for m in d.all_candidate_metrics if m["jaccard"] is not None and m["jaccard"] >= 0.30),
                        reverse=True,
                    )
                    if len(accepting_j) >= 2:
                        margins.append(accepting_j[0] - accepting_j[1])
                if d.split_flag:
                    n_split += 1
                if d.merge_flag:
                    n_merge += 1
                if d.status == "dead":
                    break
            final = tr.history[-1]
            start_members = seed_target
            end_members = final.accepted_members if final.accepted_members else frozenset()
            turnover = 1.0 - (len(start_members & end_members) / len(start_members | end_members)
                               if (start_members or end_members) else 0.0)
            traces_summary.append(dict(
                seed=int(seed), target_idx=target_idx, start_t=start_t, start_size=len(seed_target),
                final_status=final.status, final_t=final.t,
                n_unresolved_steps=n_unresolved, n_recovered_gaps=n_recovered,
                unresolved_gap_lengths=gap_lengths, max_gap_length=max(gap_lengths) if gap_lengths else 0,
                n_split_flags=n_split, n_merge_flags=n_merge,
                cumulative_turnover=turnover,
                duration_reached=final.t - start_t,
                n_ambiguous_accept_margins=len(margins),
                min_accept_margin=min(margins) if margins else None,
            ))
        per_episode.append(dict(seed=int(seed), traces=traces_summary))
    return per_episode


def main():
    rule, frozen = load_frozen_rule()
    print(f"frozen rule under test (NOT retuned): {rule.name}  spec={frozen['params']}")

    all_results = {}
    for split_name, path in SPLITS.items():
        print(f"\n=== split: {split_name} ({path.name}) ===")
        d = np.load(path, allow_pickle=True)
        seeds, r_hist_all, z_hist_all = d["seeds"], d["r_hist"], d["z_hist"]
        print(f"  episodes: {list(seeds)}")

        episode_candidates = {}
        r_hist_by_seed = {}
        for i, seed in enumerate(seeds):
            cands = run_episode_candidates(r_hist_all[i], z_hist_all[i], L_BOX)
            episode_candidates[int(seed)] = cands
            r_hist_by_seed[int(seed)] = r_hist_all[i]
            print(f"  seed {seed}: {sum(len(c) for c in cands)} total candidates over {len(cands)} steps")

        hard_neg_records = same_frame_hard_negatives(episode_candidates, r_hist_by_seed, L_BOX, rule)
        hard_neg_summary = summarize_hard_negatives(hard_neg_records, split_name)
        print(f"  same-frame hard negatives: n={hard_neg_summary['n_hard_negative_pairs']} "
              f"at-or-above-threshold={hard_neg_summary['n_at_or_above_threshold']} "
              f"({hard_neg_summary['fraction_at_or_above_threshold']:.4%})")

        trace_audit = episode_level_trace_audit(episode_candidates, rule)

        all_results[split_name] = dict(
            hard_negative_summary=hard_neg_summary,
            episode_level_trace_audit=trace_audit,
        )
        # persist the raw hard-negative records too (large but bounded; needed
        # for FINDINGS doc's "at-or-above-threshold" spot checks)
        json.dump(hard_neg_records, open(OUT_DATA / f"hard_negatives_{split_name}.json", "w"))

    json.dump(dict(frozen_rule=frozen, results=all_results),
              open(OUT_DATA / "hard_negative_validation.json", "w"), indent=2)
    print("\nwrote", OUT_DATA / "hard_negative_validation.json")


if __name__ == "__main__":
    main()
