"""Generates PARAMETER_DICTIONARY.md directly from code/configs (task brief
item 4). Every value in the output is read from a live Python object -- never
hand-copied -- so the dictionary cannot silently drift from what the code
actually runs (the failure mode task brief item 4 asks Stage 6.11 to resolve,
not repeat, from Stage 6.10's protocol/results tables).

Run after each phase adds new frozen constants; re-running is idempotent and
overwrites the previous file. Where a quantity is not yet decided (a later
phase's calibration), the row says so explicitly rather than being omitted.
"""
from __future__ import annotations

import dataclasses
import json
from pathlib import Path

from common_611 import (
    STAGE_DIR, N_BIRDS, L_BOX, R_SPEC, V_SPEC, R_SUPERSEDED, V_SUPERSEDED,
    BETA_610, S_610, RHO_BASE, OMEGA_BASE, resolved_params,
    R_PRIMARY, V_PRIMARY, COHESION_PRIMARY, SOCIAL_PRIMARY,
    R_SECONDARY, V_SECONDARY, COHESION_SECONDARY,
)
from flock_sim.model import ModelParams
from moving_flock_611 import MOORE_DEGREE
import predictive_boundary_611 as P

BASE_DESCRIPTIONS = {
    "nu": "Number of cardinal heading states (up/down/left/right). Fixed throughout Stage 6-6.11.",
    "vm": "Diagonal self-term of the base R matrix (`base_R`): weight favouring heading persistence for a bird observed at its own last heading.",
    "ca": "Collision-avoidance override magnitude: `R[o,s] = -ca` for the (observed-heading, own-heading) pairs in `SLOT_OVERRIDES` at the partner's occupied slot -- the model's separation term (flock_sim/model.py).",
    "fc": "Off-diagonal alignment weight: `R = fc * (UV4 @ UV4.T)` before diagonal/overrides -- the model's heading-alignment (cohesion-of-direction) term.",
    "beta": "precAbird: inverse-temperature (precision) of the neighbour-heading observation likelihood `neighbor_likelihood` -- how sharply a bird's *perceived* neighbour heading concentrates on the true relative geometry. NOT a spatial parameter.",
    "precB": "rho: heading-transition precision. Every column of `B[:,:,u]` is `softmax(precB * one_hot(u))` -- how deterministically a chosen action `u` is realized as the next heading.",
    "precC": "omega: preference precision. Peaks the goal-prior over a neighbour's last-observed heading in `preference_vector`.",
    "alpha": "SPM generic-solver policy-precision hyperparameter (`policy_posterior`'s self-tuning fixed point, `W = alpha/(spm_beta - u.G)`).",
    "spm_beta": "SPM generic-solver beta constant (distinct from the flocking `beta`/precAbird above). Denominator offset in the same self-tuning fixed point.",
    "n_iter": "Number of precision self-tuning iterations per policy_posterior call.",
    "n_lookahead": "T: policy length / lookahead horizon used when building G_table/Risk_table (flock_sim.active_inference.build_model).",
}

SPATIAL_DESCRIPTIONS = {
    "N": "Number of birds.",
    "L": "Torus box side length (periodic boundary in both axes).",
    "R": "Metric interaction radius: candidate partners are birds within Euclidean distance R (torus minimum image). Replaces the lattice's fixed Moore-8 neighbourhood (stage6_9 moving_flock.MovingFlock.live_edges).",
    "v": "Per-step translation speed: r_i(t+1) = r_i(t) + v * UV4[z_i(t+1)] (mod L).",
    "FOV_rule": "Directed field-of-view restriction, always active (not a free parameter, inherited from Stage 6.8 and never disabled in 6.9/6.11): bird i sees candidate partner j iff (r_j - r_i) . d_i(t) >= 0, i.e. only partners in the receiver's current forward half-plane.",
    "social": "\"raw\" (Stage 6.9 default, sum G over live partners) or \"normalized\" (Section N addition, degree-mean rescaled to k_ref). Section N found normalization does not decouple decision-gain sharpness from degree (policy_posterior's own self-tuning already does that to first order) -- kept only as a labelled comparator.",
    "social_ref_degree (k_ref)": "Reference degree normalization is rescaled to, when social=\"normalized\". Fixed a priori to the Moore neighbourhood size (8.0) the frozen R matrices were designed against -- not tuned on outcome.",
    "cohesion (fc_pos)": "Positional-cohesion term weight (Section M addition): g^pos_ij(a) = 2*fc_pos*<UV4[a], unit_bearing(j->i)>, added into the same G accumulation as G_table/Risk_table. 0.0 disables it (Stage 6.9-identical path). Declared modelling variant, not a bug fix -- see moving_flock_611.py module docstring.",
}


def fmt(v):
    return f"`{v}`" if not isinstance(v, str) else v


def main():
    lines = []
    lines.append("# Stage 6.11 Parameter Dictionary\n")
    lines.append(
        "Generated by `code/generate_parameter_dictionary_611.py` directly from "
        "`flock_sim.model.ModelParams`, `common_611.py`, `moving_flock_611.py` and "
        "(where noted) the phase-scan/gate data files. Every value below is read "
        "from a live object at generation time, not hand-copied. Re-run after each "
        "phase adds new frozen constants.\n"
    )

    lines.append("## 1. Base active-inference physics (`flock_sim.model.ModelParams`)\n")
    lines.append("Frozen since Stage 6; simulator-side only, never touched by 6.11's additions "
                  "except beta/precB/precC, which are set via the (beta, s) resolution below.\n")
    lines.append("| field | default value | meaning |")
    lines.append("|---|---|---|")
    default_pm = ModelParams()
    for f in dataclasses.fields(ModelParams):
        val = getattr(default_pm, f.name)
        lines.append(f"| `{f.name}` | {fmt(val)} | {BASE_DESCRIPTIONS.get(f.name, '')} |")
    lines.append("")

    lines.append("## 2. Stage 6.10 selected operating point and its exact resolution\n")
    lines.append(
        "RESULTS_6_10.md / SUMMARY_6_10.md report only the pair `(beta, s)`; `s` is a "
        "single scalar multiplier applied to BOTH `precB` and `precC` at simulator "
        "construction (`stage6_8_dynamic_interactions/code/episode_data.py:make_simulator`), "
        "never spelled out as resolved values in either document. Resolved here directly "
        f"via `common_611.resolved_params({BETA_610}, {S_610})`:\n"
    )
    resolved = resolved_params(BETA_610, S_610)
    lines.append("| symbol | value |")
    lines.append("|---|---|")
    lines.append(f"| beta (input) | `{BETA_610}` |")
    lines.append(f"| s (input, precision scale) | `{S_610}` |")
    lines.append(f"| RHO_BASE (precB at s=1) | `{RHO_BASE}` |")
    lines.append(f"| OMEGA_BASE (precC at s=1) | `{OMEGA_BASE}` |")
    lines.append(f"| -> ModelParams.beta | `{resolved.beta}` |")
    lines.append(f"| -> ModelParams.precB (rho) | `{resolved.precB}` |")
    lines.append(f"| -> ModelParams.precC (omega) | `{resolved.precC}` |")
    lines.append("")

    lines.append("## 3. Spatial / simulator parameters (Stage 6.9 inherited + Stage 6.11 additions)\n")
    lines.append("| parameter | value(s) | meaning |")
    lines.append("|---|---|---|")
    lines.append(f"| N | `{N_BIRDS}` | {SPATIAL_DESCRIPTIONS['N']} |")
    lines.append(f"| L (box side) | `{L_BOX}` | {SPATIAL_DESCRIPTIONS['L']} |")
    lines.append(f"| R (Stage 6.9 spec) | `{R_SPEC}` (superseded: `{R_SUPERSEDED}`) | {SPATIAL_DESCRIPTIONS['R']} |")
    lines.append(f"| v (Stage 6.9 spec) | `{V_SPEC}` (superseded: `{V_SUPERSEDED}`) | {SPATIAL_DESCRIPTIONS['v']} |")
    lines.append(f"| FOV rule | always on | {SPATIAL_DESCRIPTIONS['FOV_rule']} |")
    lines.append(f"| social | `raw` (primary), `normalized` (comparator) | {SPATIAL_DESCRIPTIONS['social']} |")
    lines.append(f"| social_ref_degree (k_ref) | `{MOORE_DEGREE}` | {SPATIAL_DESCRIPTIONS['social_ref_degree (k_ref)']} |")
    lines.append(f"| cohesion (fc_pos) | swept `{{0.0, 1.0, 2.0}}` in Section O screen | {SPATIAL_DESCRIPTIONS['cohesion (fc_pos)']} |")
    lines.append("")

    lines.append("## 4. Section O/P world-selection regime (this section is updated once selected)\n")
    scan_path = STAGE_DIR / "data" / "phase_scan_611__stage_a.json"
    if scan_path.exists():
        data = json.loads(scan_path.read_text())
        candidates = [c for c in data["cells"] if c["is_world_selection_candidate"]]
        lines.append(f"Coarse dev screen (`{scan_path.name}`): {len(data['cells'])} cells x "
                      f"{len(data['dev_seeds'])} dev seeds, nt={data['nt']}, burn_in={data['burn_in']}, "
                      f"beta={data['beta']}, s={data['s']}.\n")
        lines.append(f"World-selection candidates surviving the dev screen: **{len(candidates)}**.\n")
        if candidates:
            lines.append("| R | v | cohesion | mesoscopic_episode_fraction | collapse_probability (primary) | mean_policy_saturation |")
            lines.append("|---|---|---|---|---|---|")
            for c in sorted(candidates, key=lambda c: -c["mesoscopic_episode_fraction"]):
                lines.append(f"| {c['R']} | {c['v']} | {c['cohesion']} | "
                              f"{c['mesoscopic_episode_fraction']:.2f} | "
                              f"{c['collapse_probability']['primary']:.3f} | "
                              f"{c['mean_policy_saturation']:.3f} |")
        lines.append("")
    else:
        lines.append("**Not yet run.** See `run_phase_scan_611.py --stage a` and "
                      "`logs/regime_selection_predeclared_611.txt`.\n")

    lines.append("### 4b. SELECTED regime (held-out confirmed, see addendum in "
                  "`logs/regime_selection_predeclared_611.txt`)\n")
    lines.append("| role | R | v | cohesion (fc_pos) | social | mean policy saturation (held-out) |")
    lines.append("|---|---|---|---|---|---|")
    for role, R, v, coh, sat_path in [
        ("PRIMARY", R_PRIMARY, V_PRIMARY, COHESION_PRIMARY,
         STAGE_DIR / "data" / "phase_scan_611__stage_b_R0.9_v0.28_c1.0.json"),
        ("secondary/robustness", R_SECONDARY, V_SECONDARY, COHESION_SECONDARY,
         STAGE_DIR / "data" / "phase_scan_611__stage_b_R1.1_v0.14_c0.0.json"),
    ]:
        sat = "?"
        if sat_path.exists():
            sat = f"{json.loads(sat_path.read_text())['cell']['mean_policy_saturation']:.3f}"
        lines.append(f"| {role} | {R} | {v} | {coh} | {SOCIAL_PRIMARY} | {sat} |")
    lines.append("")

    lines.append("## 5. Passive predictive model and causal/control loop parameters\n")
    lines.append("| parameter | task-brief item | resolved value |")
    lines.append("|---|---|---|")
    for name, item, status in [
        ("Observation pool size M_obs (relational predictive model)", "6", "12 and 20 (both fit; sensitivity checked)"),
        ("Distance bins / bearing octants (relational features)", "6", f"{P.N_DIST_BINS} equal-frequency distance bins x {P.N_BEARING} bearing octants x 4 headings = {P.N_CATEGORIES} categories/stratum"),
        ("Logistic regularization C", "6", str(P.C_REG)),
        ("Boundary construction tolerance / cap", "7", f"delta_tol={P.DELTA_TOL}, min_gain={P.MIN_GAIN}, k_max={P.K_MAX}"),
        ("Certification bootstrap / tolerance", "7", f"n_boot={P.N_BOOT_CERT} (100-300 across runs), alpha={P.ALPHA_CERT}, delta={P.DELTA_SUFFICIENT}"),
        ("Louvain resolution / affinity window / kernel sigma (candidate detection)", "8", "reused unchanged from Stage 6.9 detect_69.py: W_AFFINITY=6, SIGMA=1.1, cutoff=3.3"),
        ("Causal probe budget (Stage 6.10 reference: 40 rollouts x 3 repeats)", "11", "40x3 reference; sensitivity checked at {20,40,80}x3, see causal_budget_sensitivity_611.json"),
        ("Causal decision threshold tau", "11", "0.0 (CI lower bound > 0)"),
        ("Prediction horizon tau for control authority", "13", "tau=4 primary (online loop); tau=2 is the minimum diagnostic horizon, not separately re-run"),
        ("Actuator budget K_act / control horizon T_control", "13/14", "K_act=8, T_control=24, T_release=24 (reduced from an initial 10/40/40 for this session's compute budget; disclosed in RESULTS_6_11.md)"),
        ("Re-inference cadences (pred/causal/authority)", "14", "every 12/8/8 steps respectively, with estimate-age tracked"),
        ("Attention-cap k (only if radius/speed/cohesion screen fails)", "3", "not needed -- Section O/P succeeded at the first modelling-ladder rung"),
    ]:
        lines.append(f"| {name} | {item} | {status} |")
    lines.append("")

    out_path = STAGE_DIR / "PARAMETER_DICTIONARY.md"
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
