/* copy.js - ALL on-screen copy supplied in the revision instruction, VERBATIM. Single source of truth for titles, captions, callouts, takeaways and button labels.
   (Anything the instruction did not supply and the layout needs is marked in COPY_CHANGES.md.)  CONTAINS HIDDEN INFORMATION only through the data files. */
'use strict';
const COPY = {
 acts:{1:'The organism',2:'The experiment',3:'Is it still the same organism?',4:'Changing the state on purpose',5:'What it means',A:'Appendix'},
 '1.1':{title:'Where we started',
  caption:'This model comes from Friston, Levin and colleagues (2015). Each cell carries a copy of the whole body plan and asks one question: which position in the body is mine? It guesses, moves and releases signals until its guess fits what it senses. When every cell has done this, the body is formed.',
  right:'Our version: 24 cells, a lopsided body, a little random jitter, and no built-in sense of absolute position.',
  callouts:['8 identical cells, all starting near the middle.','Each cell has picked a position and is moving to it.','The finished body: head, middle and tail.','Our organism, already formed.'],
  takeaway:'The body is what you get when every cell has found its place.'},
 '1.2':{title:'What one cell knows and does',
  caption:'Click any cell. Inside it are two guesses we can never see directly: which position it has, and which of two group states the organism is in. It learns about the world only through the signals it senses, and it affects the world only by moving and releasing signals.',
  callouts:['Inside: the cell\'s guesses. Hidden from everyone.','Senses and actions: the cell\'s only contact with the rest.','Everything else: the other cells and the experimenter.'],
  takeaway:'Each cell meets the world only through what it senses and what it does. We call that layer the cell\'s blanket.'},
 '1.3':{title:'The signals cells make',
  caption:'',
  buttons:['Body signals','Head-to-tail signal','Memory signals','Yellow marker'],
  texts:['Three signals that tell a cell what kind it is: head, middle, side or tail. They hold the body\'s shape.',
         'A signal that is weak at the head and strong at the tail. Cells use it to tell front from back.',
         'Every cell releases a blue and a pink signal. The mix it releases shows which group state it believes in. These signals have no effect on the body\'s shape.',
         'A visible marker that shows the group state. It lights one row of cells: one side in the blue state, the other side in the pink state. No cell reacts to it. It is there so we can see the state.'],
  takeaway:'Some signals build the body. Others carry a memory. The marker lets us see the memory.'},
 '1.4':{title:'One body, two states',
  caption:'These two organisms are identical cell for cell: same positions, same cell types. They differ only in their group state, blue on the left and pink on the right. Press Overlay to place one on top of the other.',
  callouts:['Same cells, same places.','Only the memory signals and the yellow marker differ.'],
  takeaway:'One body, two states. Each lasts as long as we watch.'},
 '1.5':{title:'One cell forgets, the group remembers',
  caption:'A cell\'s memory fades unless its neighbours keep telling it the same thing. We start a single cell, a group of four and a whole organism in the blue state, and watch. Shading shows each cell\'s hidden memory.',
  callouts:['Alone, a cell soon becomes undecided.','A small group holds on for a while, but can lose it.','The whole organism keeps its state.'],
  takeaway:'The memory belongs to the group, not to any one cell.'},
 '2.1':{title:'The dish and the tools',
  caption:'Each experiment is a dish with one organism in it, placed at a random spot and angle. We have the kinds of tools a lab biologist would have.',
  tools:[['Light','shine on a chosen area. There are five lights and each affects cells differently.'],['Bath','add a signal to the whole dish.'],['Pipette','release a signal at one point.'],['Tweezers','pull one cell away.'],['Surgery','remove, replace or cut cells, or put two organisms together.']],
  takeaway:'We can poke the organism in the ways a lab could.'},
 '2.2':{title:'How each tool works in the model',
  caption:'Distances are in cell-widths: the usual distance between two neighbouring cells.',
  buttons:['Cut','Pull out a cell','Replace a cell','Merge two organisms','Light','Bath'],
  texts:['We draw a line across the body. Every cell on one side is moved 7 cell-widths away at once, as if cut and pulled apart. The cells keep their guesses and carry on.',
         'One cell is picked up and put down 8 cell-widths away from the body. Then we let go and watch.',
         'One cell is removed and a brand-new cell is put in the same spot. The newcomer starts with no idea of its position, releases nothing yet, and is undecided about the group state. It gets a new name tag.',
         'We put two whole organisms side by side in one dish, close enough to sense each other.',
         'While the light is on, the cells inside the lit area are made to release extra of one signal, or for some lights, to move or sense differently. The light fades in and out smoothly. Cells outside the lit area are not touched.',
         'Extra signal is added evenly everywhere in the dish.'],
  takeaway:'Every tool acts from the outside. What happens next is up to the cells.'},
 '2.3':{title:'What an observer gets to see',
  caption:'Nobody gets to see inside the cells. An observer gets one of these views, from easiest to hardest. Everything about identity and control in this demo was worked out from these views alone.',
  panels:['Tracked cells','Unlabelled dots','Microscope image (glow)','Microscope image (cell markers)','Hidden'],
  callouts:['We know which dot is which cell over time.','Only dots. Which cell is which must be worked out.','The signals blur together. Single cells can\'t be told apart.','Each cell shows up as a spot.','Positions, guesses and memory. Used only to check answers afterwards.'],
  outline:'show outline',
  takeaway:'Identity has to be worked out from what can be seen.'},
 '3.1':{title:'Which cells belong together',
  caption:'To follow an organism we first decide which cells belong to it. Cells that are close neighbours are linked, and each linked group counts as one organism, with an outline drawn around it. Here the same dish is outlined from each view. Watch what happens at the cut.',
  callouts:['All four views find one organism.','From tracked cells and dots we see two organisms. The blurry image has trouble splitting them.','The outline is our rule for which cells count as the organism.'],
  button:'How is the outline drawn?',
  steps:['Points','Links','Groups','Outline','Head-to-tail axis'],
  drawn:'drawn by the blind analysis',
  takeaway:'The outline says which cells belong. It is a grouping we choose, not something the cells define.'},
 '3.2':{title:'Four ways an organism can change',
  caption:'We track four things separately: which cells are in it, its shape, its pattern of signals, and its group state. The same-body check passes only if the same cells are there and the shape stays within the range an untouched organism shows by itself. Pick an example.',
  buttons:['Untouched','Cut','Light switch'],
  callouts:{Untouched:'Everything stays inside its normal range (grey band).',Cut:'Cells leave and the shape breaks, so the same-body check fails.','Light switch':'Same cells, same shape, so the check passes. Only the pattern and the group state change.'},
  takeaway:'Changing the group state is not the same as changing the organism.'},
 '3.3':{title:'Replacing every cell',
  caption:'Every 100 time units we remove one of the original cells and put a brand-new, naive cell in its place, in random order, until all 24 are new. Then we watch for 400 more time units.',
  callouts:['A newcomer copies the group state from its neighbours within about 2 time units.','No original cell is left.','The group state survived. The shape did not.'],
  counter:'Original cells left',
  takeaway:'The memory outlived every cell that started it. The shape did not, and that is something still to fix.'},
 '3.4':{title:'Finding the two states without being told',
  caption:'A program that saw the dishes only from the outside sorted 260 untouched organisms by their signal patterns. It found two groups by itself. Press T to colour them by the true hidden state.',
  callouts:['Two clear groups.','They match the true states 99 to 100 percent of the time.','It first took the two for mirror images. They are not: same body, with the marker on the other row.'],
  takeaway:'The two states can be found from the outside alone.'},
 '4.1':{title:'Which light does something',
  caption:'The blind controller is a program that sees only what an observer sees. It started without knowing what the five lights do. Here each light shines on the middle of the same organism, for the same time and strength.',
  rows:['Starting in the blue state','Starting in the pink state'],
  callouts:['One light flips blue to pink. A different one flips pink to blue.','The other lights move cells or change the body, without flipping the state.'],
  button:'Reveal what each light does',
  takeaway:'Two lights change the group state, each in one direction only.'},
 '4.2':{title:'Where and how long to shine',
  caption:'The controller tried shining on different parts of the body for different lengths of time. The map shows how much light was needed at each spot; darker means more.',
  callouts:['The middle needs the least.','The tail end needs about three to four times more.','Flashes shorter than 4 time units never work, however bright.'],
  clips:['Middle','Tail end (same amount of light)'],
  takeaway:'Where you shine matters more than how bright. And the light has to stay on long enough.'},
 '4.3':{title:'Three things called a boundary',
  caption:'The word boundary gets used for three different things. Only one of them is how control works.',
  panels:[['Outline','Which cells belong to the organism. It is drawn by us, from what we can see.'],
          ['Blanket','The inputs and outputs that separate an inside from an outside. Each cell has one. Inside the organism, the memory is separated from the body in the same way: the body never listens to the memory.'],
          ['Interface','Where a push gets in. A lit patch acts through its edge: the more contact its cells have with the rest, the less light is needed. That is why the middle is cheapest.']],
  takeaway:'Control works through the interface, not the outline.'},
 '4.4':{title:'The switch',
  caption:'Four copies of the same organism, run with identical random jitter. From left: the controller\'s choice; the same amount of light on a random spot; the same amount spread over the whole body; no light.',
  callouts:['All four start the same.','Light on the middle.','No cell moves.','Past the tipping point, so the light goes off.','The organism finishes the switch by itself.','It stays switched.','Same light, wrong spot: a small wobble, then back.','Same light, spread thin: nothing happens.'],
  hint:'Press T to show each cell\'s hidden memory, and watch the change spread out from the lit patch.',
  takeaway:'A small, short light in the right place switches the state for good. No cell moves.'},
 '4.5':{title:'How well it works',
  caption:'We tested the controller on 60 new dishes it had never seen. Each dish was also run with the other strategies and with no light.',
  labels:['Controller','One flash, tuned in advance','Whole body, bright','Whole body, same total light','Random spot, same light','No light / fake light'],
  line:'Checked against the hidden truth: 57 of 60 switched and stayed switched, and no organism was ever damaged. The controller used about 12 percent more light than the true minimum; the tuned flash about 54 percent more; the bright whole-body light almost 3 times more.',
  callouts:['The controller works about 95 percent of the time, and the organism always stays the same organism.','A random spot with the same light: 7 percent.','Lighting the whole body works, but needs almost 4 times more light.','A single flash tuned in advance works as well. These dishes are too alike for adjusting on the fly to pay off.'],
  failure:'Here the controller stopped too early. The organism had not passed the tipping point and drifted back.',
  takeaway:'It works reliably and aims well. It does not yet beat a well-tuned single flash.'},
 '5.1':{title:'Three groups compared',
  caption:'We used the same tests on three systems: a simulated bird flock from our earlier work, the published cell model, and our organism.',
  columns:['Bird flock','Published cell model','Our organism'],
  rows:[['Can we follow it over time?','yes','yes','yes'],
        ['Does poking it change it?','sometimes, unpredictably','only while poked','yes'],
        ['Does the change last?','no','no, it returns (or breaks)','yes'],
        ['Does where you poke matter, on new examples?','no','not tested this way','yes'],
        ['Can we change its state and keep the same organism?','no','no','yes']],
  takeaway:'The same tests tell apart a group you can\'t steer from one you can.'},
 '5.2':{title:'What biologists could test',
  caption:'',
  cards:['A memory can outlive the cells that made it. Replace cells gradually and see whether a tissue keeps its pattern.',
         'Small pieces forget faster. Cut tissue into pieces of different sizes and see which keep their pattern.',
         'There is a minimum time to reprogram. Below it, no strength works. Vary the length of a light or drug pulse.',
         'Push where cells are most connected. Compare stimulating different regions with how strongly the cells there are coupled.',
         'Cells that listen to their own signal hold on too tightly. Block self-signalling and see whether patterns become easier to change.'],
  next:['Make the memory change the body\'s shape, not just its pattern.','Test the controller on harder, more varied organisms.','Control from microscope images instead of tracked cells.','Use the same boundary measures on all three systems.'],
  takeaway:'A group memory that can be switched without changing the group is something real tissue may have, and it can be tested.'},
 'A':{title:'Why the memory can be switched',
  caption:'In an earlier version, each cell counted its own signal as evidence, so its belief kept confirming itself and nothing could switch it. Here a cell listens only to its neighbours. A lone cell forgets; a group holds two stable states; a strong enough push moves it from one to the other.',
  r:'how fast a lone cell forgets', g:'how strongly neighbours persuade it', readout:'two stable states when g is more than 4 times r',
  symbols:['l = a cell\'s leaning toward blue (positive) or pink (negative)','f = the share of blue signal arriving from its neighbours','r = how fast a lone cell forgets','g = how strongly neighbours persuade it'],
  takeaway:''},
 'B':{title:'Words we use', caption:'', takeaway:''},
 'C':{title:'About the data', caption:'', takeaway:''}
};
