"""B5 viewer pages for package v3 (OBSERVABLE build: only what the package contains; no hidden tier, no analysis)."""
import sys, os, json, csv, base64; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); TB = os.path.dirname(HERE); MORPH = os.path.dirname(TB); PKG = os.path.join(MORPH, 'testbed_blind_v3'); OUT = os.path.join(TB, 'viewer_pkg3'); os.makedirs(OUT, exist_ok=True)
def b64(a): return base64.b64encode(np.ascontiguousarray(a).tobytes()).decode()
def page(run, t_lo, t_hi, o3_every, title, sub):
    cat = {r['run']: r for r in csv.DictReader(open(f'{PKG}/catalog.csv'))}[run]; o1 = np.load(f'{PKG}/runs/{run}_O1.npz'); ptr = o1['frame_ptr']; t1 = o1['t']; keep = [k for k in range(len(t1)) if t_lo <= t1[k] <= t_hi]
    fr = [dict(t=float(t1[k]), xy=np.round(o1['xy'][ptr[k]:ptr[k + 1]], 3).tolist(), lv=np.round(o1['level'][ptr[k]:ptr[k + 1]], 3).tolist()) for k in keep]
    ob = np.load(f'{PKG}/runs/{run}_O3b.npz'); oc = np.load(f'{PKG}/runs/{run}_O3c.npz'); tb = ob['t']; tc = oc['t']
    selb = [i for i in range(len(tb)) if t_lo <= tb[i] <= t_hi][::o3_every]; selc = [i for i in range(len(tc)) if t_lo <= tc[i] <= t_hi][::o3_every]
    imb = ob['image'][selb].astype(np.float32); gm = imb.reshape(len(selb), 4, -1).max(2).max(0)[None, :, None, None] + 1e-9; Ub = np.clip(255 * imb / gm, 0, 255).astype(np.uint8); Uc = oc['image'][selc]
    d = dict(run=run, cond=cat['condition'], arm=cat['arm'], fine=cat['fine_window'], frames=fr, tb=[float(tb[i]) for i in selb], tc=[float(tc[i]) for i in selc], b=dict(shape=list(Ub.shape[1:]), b64=[b64(Ub[i]) for i in range(len(Ub))]), c=dict(shape=list(Uc.shape[1:]), b64=[b64(Uc[i]) for i in range(len(Uc))]), fov_b=float(cat['fov']), fov_c=float(cat['fov_c']))
    html = HTML.replace('__TITLE__', title).replace('__SUB__', sub).replace('__DATA__', json.dumps(d)); p = os.path.join(OUT, f'{title.split()[0]}_{run}.html'); open(p, 'w').write(html); return p
HTML = """<!doctype html><html><head><meta charset=utf-8><title>__TITLE__</title><style>body{font-family:system-ui;margin:0;background:#fafafa}header{padding:8px 14px;background:#fff;border-bottom:1px solid #ccc}.ban{background:#e2f0e2;color:#1c5a1c;font-weight:600;padding:5px 14px}#ctl{padding:6px 14px}canvas{background:#fff;border:1px solid #ccc;margin:5px}.row{display:flex;flex-wrap:wrap}.note{font-size:12px;color:#444;padding:4px 14px}</style></head><body>
<header><b>__TITLE__</b> &nbsp; <span style=color:#555>__SUB__</span></header><div class=ban>OBSERVABLE BUILD - package data only (no analysis, no hidden quantities)</div>
<div id=ctl><button id=play>play</button> <input id=sl type=range min=0 max=0 value=0 style="width:520px"> <span id=tl></span> &nbsp; colour cells by column <select id=col></select> &nbsp; image channel O3b <select id=cb></select> O3c <select id=cc></select></div>
<div class=row><canvas id=a width=380 height=330></canvas><canvas id=b width=330 height=330></canvas><canvas id=c width=330 height=330></canvas></div><div class=row><canvas id=s width=1050 height=170></canvas></div>
<div class=note id=info></div><script id=data type=application/json>__DATA__</script><script>
const D=JSON.parse(document.getElementById('data').textContent);const F=D.frames;const N=F.length;const sl=document.getElementById('sl');sl.max=N-1;let cur=0,playing=false;
for(let j=0;j<7;j++){document.getElementById('col').add(new Option('column '+j,j));}for(let j=0;j<D.b.shape[0];j++)document.getElementById('cb').add(new Option('channel '+j,j));for(let j=0;j<D.c.shape[0];j++)document.getElementById('cc').add(new Option(j==0?'0 (cell marker)':'channel '+j,j));
const dec=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const IB=D.b.b64.map(dec),IC=D.c.b64.map(dec);
let xs=[],ys=[];F.forEach(f=>f.xy.forEach(p=>{xs.push(p[0]);ys.push(p[1])}));const pad=2,x0=Math.min(...xs)-pad,x1=Math.max(...xs)+pad,y0=Math.min(...ys)-pad,y1=Math.max(...ys)+pad;const W=380,H=330,sc=Math.min(W/(x1-x0),H/(y1-y0));const tx=x=>(x-x0)*sc,ty=y=>H-(y-y0)*sc;
const all=[];for(let j=0;j<7;j++){all.push(F.map(f=>f.lv.reduce((s,r)=>s+r[j],0)/f.lv.length))}
function nearest(arr,t){let b=0,bd=1e9;arr.forEach((u,i)=>{const d=Math.abs(u-t);if(d<bd){bd=d;b=i}});return b}
function imgDraw(cv,buf,shape,ch,fov,cx){const [C,Hh,Ww]=shape;const o=cx.createImageData(Ww,Hh);let mx=1;const off=ch*Hh*Ww;for(let i=0;i<Hh*Ww;i++)mx=Math.max(mx,buf[off+i]);for(let i=0;i<Hh*Ww;i++){const v=255*buf[off+i]/mx;o.data[4*i]=v;o.data[4*i+1]=v;o.data[4*i+2]=v;o.data[4*i+3]=255}const t=document.createElement('canvas');t.width=Ww;t.height=Hh;t.getContext('2d').putImageData(o,0,0);cx.imageSmoothingEnabled=false;cx.drawImage(t,0,0,cv.width,cv.height)}
function draw(){const f=F[cur];const a=document.getElementById('a').getContext('2d');a.clearRect(0,0,W,H);const j=+document.getElementById('col').value;const v=f.lv.map(r=>r[j]);const mn=Math.min(...all[j]),mx=Math.max(...all[j].concat(v));const vals=F.flatMap(g=>g.lv.map(r=>r[j]));const lo=Math.min(...vals),hi=Math.max(...vals);
 f.xy.forEach((p,i)=>{const u=(v[i]-lo)/(hi-lo+1e-9);a.beginPath();a.arc(tx(p[0]),ty(p[1]),6,0,6.3);a.fillStyle='rgb('+Math.round(255*u)+','+Math.round(80+60*(1-u))+','+Math.round(255*(1-u))+')';a.fill();a.strokeStyle='#333';a.stroke()});a.fillStyle='#000';a.fillText('O1 cells, colour = column '+j+' (blue low, red high)   t = '+f.t,6,12);
 const ib=nearest(D.tb,f.t),ic=nearest(D.tc,f.t);imgDraw(document.getElementById('b'),IB[ib],D.b.shape,+document.getElementById('cb').value,D.fov_b,document.getElementById('b').getContext('2d'));imgDraw(document.getElementById('c'),IC[ic],D.c.shape,+document.getElementById('cc').value,D.fov_c,document.getElementById('c').getContext('2d'));
 const s=document.getElementById('s').getContext('2d');s.clearRect(0,0,1050,170);const t0=F[0].t,t1=F[N-1].t;const X=t=>40+(t-t0)/(t1-t0+1e-9)*990;const cols=['#d62728','#1f77b4','#2ca02c','#9467bd','#ff7f0e','#8c564b','#17becf'];all.forEach((ser,k)=>{const mn=Math.min(...ser),mxx=Math.max(...ser);s.strokeStyle=cols[k];s.beginPath();ser.forEach((y,i)=>{const yy=160-(y-mn)/(mxx-mn+1e-9)*150;i?s.lineTo(X(F[i].t),yy):s.moveTo(X(F[i].t),yy)});s.stroke();s.fillStyle=cols[k];s.fillText('col '+k,2,12+11*k)});s.strokeStyle='#000';s.beginPath();s.moveTo(X(f.t),0);s.lineTo(X(f.t),170);s.stroke();
 document.getElementById('tl').textContent=' t = '+f.t+'  ('+cur+'/'+(N-1)+')';document.getElementById('info').textContent='run '+D.run+' | condition '+D.cond+' | arm '+D.arm+' | frame spacing in this window: '+(N>1?(F[1].t-F[0].t).toFixed(1):'-')+' tu | fine window '+D.fine;sl.value=cur}
sl.oninput=()=>{cur=+sl.value;draw()};['col','cb','cc'].forEach(i=>document.getElementById(i).onchange=draw);document.getElementById('play').onclick=()=>{playing=!playing};(function loop(){let last=0;function f(ts){if(playing&&ts-last>80){cur=(cur+1)%N;draw();last=ts}requestAnimationFrame(f)}requestAnimationFrame(f)})();draw();</script></body></html>"""
def main():
    cat = list(csv.DictReader(open(f'{PKG}/catalog.csv'))); nat = [r for r in cat if r['condition'] == 'N0'][0]['run']; sw = [r for r in cat if r['condition'].startswith('T') and r['arm'] == 'treated'][0]
    print(page(nat, 0, 240, 2, 'natural_fine natural dish at 1 tu', 'first 240 tu of a long natural run, 1 tu frames'))
    print(page(sw['run'], 20, 140, 3, 'light_run light run at 0.5 tu', f"{sw['condition']} treated; fine window {sw['fine_window']}; frames every 0.5 tu"))
if __name__ == '__main__': main()
